
data_root: ./data/seg_single_view
checkpoint_path: ./checkpoints/epoch_0250_iter_050000.pth # Path to the pre-trained checkpoint
data_type: seg
overwrite_embeddings: True
no_validation: True
sample_observations_train: 0
freeze_networks: True
img_sidelengths: 128
output_sidelength: 128
batch_size_per_img_sidelength: 8
max_steps_per_img_sidelength: 200000
out_channels: 19
