data_root: ./data/seg_face
logging_root: ./log/
img_sidelength: 128
output_sidelength: 128
batch_size: 8
max_steps: 400000
sample_instances_train: 0-665
sample_instances_val: 0-50
sample_observations_train: 0-30
sample_observations_val: 31-35
out_channels: 20